使用numpy对数组或矩阵进行拼接

In [1]:
import numpy as np

# 对list类型拼接

In [2]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
list2 = [[11,12,13],[14,15,16],[17,18,19]]

In [3]:
# 行上进行拼接
np.hstack([list1, list2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [4]:
# 列上进行拼接
np.vstack([list1, list2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [8]:
# 对numpy矩阵类型进行拼接
a = np.floor(10*np.random.rand(2,2))
b = np.floor(10*np.random.rand(2,2))
print('a:', a)
print('b:', b)

a: [[9. 6.]
 [9. 4.]]
b: [[1. 7.]
 [4. 2.]]


In [9]:
# 行上进行拼接
np.hstack([a, b])

array([[9., 6., 1., 7.],
       [9., 4., 4., 2.]])

In [10]:
# 列上进行拼接
np.vstack([a, b])

array([[9., 6.],
       [9., 4.],
       [1., 7.],
       [4., 2.]])