In [1]:
# -*- coding: utf-8 -*-
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
 
word_to_ix = {'hello': 0, 'world': 1}
embeds = nn.Embedding(2, 5)
hello_idx = torch.LongTensor([word_to_ix['hello']])
hello_idx = Variable(hello_idx)
hello_embed = embeds(hello_idx)
print(hello_embed)

tensor([[-1.0009,  0.1463, -0.1994, -0.5982, -0.6459]],
       grad_fn=<EmbeddingBackward>)


In [27]:
world_idx = torch.LongTensor([[0,1],[1,0]])
world_idx = Variable(world_idx)
world_embed = embeds(world_idx)
print(world_embed)

tensor([[[-1.0009,  0.1463, -0.1994, -0.5982, -0.6459],
         [ 0.0733,  1.8930,  0.3297, -3.0341, -0.4301]],

        [[ 0.0733,  1.8930,  0.3297, -3.0341, -0.4301],
         [-1.0009,  0.1463, -0.1994, -0.5982, -0.6459]]],
       grad_fn=<EmbeddingBackward>)


In [5]:
torch.cat([hello_embed, world_embed], 1)

tensor([[-1.0009,  0.1463, -0.1994, -0.5982, -0.6459,  0.0733,  1.8930,  0.3297,
         -3.0341, -0.4301]], grad_fn=<CatBackward>)

In [21]:
x2 = torch.FloatTensor([[1,2,3,4,5,6,7]])

In [22]:
torch.cat([hello_embed, x2], 1)

tensor([[-1.0009,  0.1463, -0.1994, -0.5982, -0.6459,  1.0000,  2.0000,  3.0000,
          4.0000,  5.0000,  6.0000,  7.0000]], grad_fn=<CatBackward>)

tensor([[-0.9277,  2.0393,  0.1304, -3.6323, -1.0760]], grad_fn=<AddBackward0>)

In [19]:
x1 = torch.FloatTensor([[-1.0009,  0.1463, -0.1994, -0.5982, -0.6459], [-0.9277,  2.0393,  0.1304, -3.6323, -1.0760]])

In [20]:
torch.cat([x1, x1], 1)

tensor([[-1.0009,  0.1463, -0.1994, -0.5982, -0.6459, -1.0009,  0.1463, -0.1994,
         -0.5982, -0.6459],
        [-0.9277,  2.0393,  0.1304, -3.6323, -1.0760, -0.9277,  2.0393,  0.1304,
         -3.6323, -1.0760]])