# 使用sklearn将数据集划分为训练集和测试集

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# 生成样本数据
X, y = np.arange(30).reshape((15,2)), np.arange(15)
print('x:\n{}\n y:\n{}'.format(X ,y))

x:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]
 y:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
# 划分数据集, 参数说明：特征数据，标签数据，划分比例，随机种子, 将数据集换分为9:1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

[[ 0  1]
 [26 27]
 [10 11]
 [16 17]
 [ 4  5]
 [ 2  3]
 [28 29]
 [ 8  9]
 [14 15]
 [20 21]
 [24 25]
 [ 6  7]
 [12 13]] 
 [ 0 13  5  8  2  1 14  4  7 10 12  3  6]
[[18 19]
 [22 23]] 
 [ 9 11]


# train_test_spilt 按照比例划分数据集

设置stratify参数，可以按照标签或者某一维特征的比例划分数据集

In [10]:
X = np.arange(20)
y = ['A','B','A','A','A','B','A','B','B','A','A','B','B','A','A','B','A','B','A','A']
print('number of A:{}, B:{}'.format(y.count('A'), y.count('B')))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, stratify=y, random_state=42)
print('test number of A:{}, B:{}'.format(y_test.count('A'), y_test.count('B')))

number of A:12, B:8
test number of A:3, B:2
